### ISSUE TITLE
error: 'class nvinfer1::IBuilder' has no member named 'buildSerializedNetwork'

### ISSUE THREAD

**Issue by huyuanchao** [HaohaoNJU/CenterPoint#17]
i want to carry out the trt engin inference according to your opencode(https://github.com/Abraham423/CenterPoint)

but i can't make successfully.

when i run  cmake .. && make
always get the following errors,can you give me a compiled docker image ? or  tell me the details about how to solve it:

src/centerpoint.cpp:134:48: error: 'class nvinfer1::IBuilder' has no member named 'buildSerializedNetwork'

  134 |     SampleUniquePtr<IHostMemory> plan{builder->buildSerializedNetwork(*network, *config)};

      |                                                ^~~~~~~~~~~~~~~~~~~~~~

/data/CUDA-PointPillars-main/CenterPoint_int8/src/centerpoint.cpp:134:89: error: no matching function for call to 'std::unique_ptr<nvinfer1::IHostMemory, samplesCommon::InferDeleter>::unique_ptr(<brace-enclosed initializer list>)'

  134 |     SampleUniquePtr<IHostMemory> plan{builder->buildSerializedNetwork(*network, *config)};

**Comment by sunnyln** [comment]
It seems like TensorRT version problem. What is your TensorRT version?

**Comment by Abraham423** [comment]
vTensorRT : 8.0.1.6
vUbuntu : 18.04
check it out ~
