### ISSUE TITLE
What is the input for `tools/generate_input_data.py`

### ISSUE THREAD

**Issue by StiphyJay** [HaohaoNJU/CenterPoint#25]
As mentioned in title, when I run inference, I need give the parameter --filePath=/PATH/TO/DATA. However, you see filePath refers to input bin files generated by tools/generate_input_data.py. So, what is the input data for tools/generate_input_data.py.

Looks for your reply!
Thx!

**Comment by HaohaoNJU** [comment]
Hi, this project assumes you've previously generated the pkl files according to [here](https://github.com/tianweiy/CenterPoint/blob/master/docs/WAYMO.md) 
Then you'll have  dir tree like this ：
```
$waymo_opensets 
  - train 
    -- lidar
    -- annos
  - val
    -- lidar 
    -- annos
  ...
```
you can choose the `pkl` files in `val/lidar/` from a certain sequence, and generate the `bin` files .

**Comment by StiphyJay** [comment]
> here

OK. Got it. Thanks for your reply! It's very useful!

**Comment by StiphyJay** [comment]
> Hi, this project assumes you've previously generated the pkl files according to [here](https://github.com/tianweiy/CenterPoint/blob/master/docs/WAYMO.md) Then you'll have dir tree like this ：
> 
> ```
> $waymo_opensets 
>   - train 
>     -- lidar
>     -- annos
>   - val
>     -- lidar 
>     -- annos
>   ...
> ```
> 
> you can choose the `pkl` files in `val/lidar/` from a certain sequence, and generate the `bin` files .

OK. Got it. Thanks for your reply! It's very useful!
